Bankproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("bank/",include("bankapp.urls")),
    path("credentials/",include("credentials.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankapp/urls.py
from django.urls import path
from . import views
app_name="bankapp"

urlpatterns = [
    path("",views.demo,name="home"),
    path("formfilling/",views.form_view,name="forms"),
    path("application/",views.newdemo,name="application"),
    path("logout/",views.logout,name="signout"),
]

credentials/urls.py
from django.urls import path
from . import views
app_name="credentials"

urlpatterns = [
    path("register/",views.register,name="signup"),
    path("login/",views.login,name="signin"),
   
]

bankapp/models.py
from django.db import models

# Create your models here.

credentials/models.py
from django.db import models

# Create your models here.
 

bankapp/forms.py
from django import forms

DISTRICT_CHOICES = [
    ('Alappuzha', 'Alappuzha'),
    ('Kollam', 'Kollam'),
    ('Ernakulam', 'Ernakulam'),
    ('Wayanad', 'Wayanad'),
    ('Thrissur', 'Thrissur')
    # Add more district choices as needed
]

BRANCH_CHOICES = {
    'Alappuzha': ['Changanassery', 'Vandanam', 'Kalarcode'],
    'Kollam': ['Pathanapuram', 'Karunagapally', 'Thodiyoor'],
    'Ernakulam': ['Mattanchery', 'Thoppumbady', 'Kumbalangi'],
    'Wayanad': ['Kalpetta', 'Padinjarathara', 'Meenangadi'],
    'Thrissur': ['Cheruthurithy', 'Vadakkekad', 'Punnayurkkulam']
    # Define sub-areas for other districts
}

ACCOUNT_CHOICES = [
    ('Savings Account', 'Savings Account'),
    ('Current Account', 'Current Account'),
    ('Other', 'Other')
    # Add more account type choices as needed
]

MATERIALS_PROVIDED_CHOICES = [
    ('Debit Card', 'Debit Card'),
    ('Credit Card', 'Credit Card'),
    ('Cheque Book', 'Cheque Book'),
    # Add more materials provided choices as needed
]

class ApplicationForm(forms.Form):
    name = forms.CharField(max_length=100, label='Name')
    dob = forms.DateField(label='Date of Birth',widget=forms.DateInput(attrs={'type': 'date'}))
    age = forms.IntegerField(label='Age')
    gender = forms.ChoiceField(choices=[('Male', 'Male'), ('Female', 'Female')], widget=forms.RadioSelect, label='Gender')
    phone_number = forms.CharField(max_length=15, label='Phone Number')
    email = forms.EmailField(label='Email')
    address = forms.CharField(widget=forms.Textarea,label='Address')
    district = forms.ChoiceField(choices=DISTRICT_CHOICES, label='District',widget=forms.Select(attrs={'id': 'id_district'}))
    branch = forms.CharField(max_length=200, label='Branch', required=False, widget=forms.Select(attrs={'id': 'id_branch'}))
    account_type = forms.ChoiceField(choices=ACCOUNT_CHOICES, label='Account Type')
    materials_provided = forms.MultipleChoiceField(
        choices=MATERIALS_PROVIDED_CHOICES,
        widget=forms.CheckboxSelectMultiple,
        label='Materials Provided'
    )

bankapp/views.py
from django.shortcuts import redirect, render
from django.contrib import auth,messages
from .forms import ApplicationForm

# Create your views here.

def demo(request):
    return render(request,"index.html")

def form_view(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            messages.success(request, 'Application Accepted !!!')
            return redirect('bankapp:forms')
    else:
        form = ApplicationForm()
    return render(request, 'home.html', {'form': form})


def newdemo(request):
    return render(request,"demo.html")  

def logout(request):
    auth.logout(request)
    return redirect('bankapp:home')  

credentials/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib import messages,auth
from django.urls import reverse
# Create your views here.

def register(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        cpassword=request.POST["confirm_password"]

        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username is already taken !!!")
                return redirect('credentials:signup')
            
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save()
                messages.info(request,"registration completed !!!")
                print("user created")    
        else:
            messages.info(request,"password incorrect !!!")
            return redirect('credentials:signup')

        return redirect('credentials:signin')   


    return render(request,"register.html")


def login(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]

        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('bankapp:application')
        else:
            messages.info(request,"invalid username !!!")
            return redirect('credentials:signin')
    return render(request,"login.html")    

templates/demo.html
{% extends 'nav.html' %}
{% load static %}
{% block body %}
<div class="banner_main">
    <h1 class="banner_taital" style="color: rgb(62, 62, 221);">Presenting <br>Federal 24 7</h1>
    <h1 class="banner_text" style="font-size: 25px;">Now open a savings account of your <br> choice anytime without visiting the Bank.</h1>
    <div class="btn_main">
      <div class="more_bt" style="width: 300px;"><a href="{% url 'bankapp:forms' %}">Open an account</a></div>
    </div>
  </div>
  </div>
  <div class="header_right float-end" style="position: relative;">
    <img src="{% static 'images/application.png' %}" class="banner_img" style="position: absolute; top: -450px;">
  </div>
  </div>
  <!--header section end -->
  <!--about section start -->
  <div class="services_section layout_padding">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h1 class="services_taital">Stay connected enjoy peace of mind</h1>
          <p class="services_text">Download the FED One Mobile App and simplify your banking. Discover quick, simple and
            convenient way to take command of your bank account, on your mobile phone.</p>
          <div class="moremore_bt"><a href="#">Download</a></div>
        </div>
        <div class="col-md-4">
          <div><img src="{% static 'images/img-1.png' %}" class="image_1"></div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/home.html
{% extends 'nav.html' %}
{% load static %}
{% block body %}


<div class="formbold-main-wrapper">

  <div class="formbold-form-wrapper">
    <div style="position: relative;">
      <h1 style="text-align: center; top: -40px; color: rgb(62, 62, 221); font-size: 50px;">Open an account
        <hr>
      </h1>
    </div>
    <img src="{% static 'images/federal-banner.png' %}" style="width: 1905px; height: 300px;" class="mb-5">

    <h1 style="text-align: center; color:orangered;">Fill the form</h1>
    <hr>
    <div class="app">
    <form action="{% url 'bankapp:forms' %}" method="post">
      {% csrf_token %}
      
      <label for="id_name">Name :</label>
      {{form.name}}
      <br>

      <label for="id_dob">Date of birth :</label>
      {{form.dob}}
      <br>

      <label for="id_age">Age :</label>
      {{form.age}}
      <br>

      <label for="id_gender">Gender :</label>
      {{form.gender}}
      <br>

      <label for="id_phone_number">Phone number :</label>
      {{form.phone_number}}
      <br>

      <label for="id_email">Email :</label>
      {{form.email}}
      <br>

      <label for="id_address">Address :</label>
      {{form.address}}
      <br>

      <label for="id_district">District :</label>
      {{form.district}}
      <br>

      <label for="id_branch">Branch :</label>
      {{form.branch}}
      <br>

      <label for="id_account_type">Account Type :</label>
      {{form.account_type}}
      <br>

      <label for="id_materials_provided">Materials Provided:</label><br>
        {% for material in form.materials_provided %}
            <label for="{{ material.id }}">{{ material.choice_label }}</label>
            {{ material.tag }}
            <br>
        {% endfor %}

        <br>




      <!-- submit logout -->
      <div class="">
        <button type="submit" class="btn btn-light rounded-pill fw-bolder mb-1">Submit</button>
        <a href="{% url 'bankapp:home' %}" type="button" class="btn btn-light rounded-pill fw-bolder mb-1">logout</a>
      </div>
      <!-- ends -->

    </form>
  </div>

    {% for msg in messages %}

    <h3 style="margin-top: 20px; text-align: center;">{{msg}}</h3>

    {% endfor %}
  </div>
</div>

<script>
  const districtSelect = document.getElementById('id_district');
  const branchSelect = document.getElementById('id_branch');
  
  // Define branch options for each district
  const branchOptions = {
    'Alappuzha': ['Changanassery', 'Vandanam', 'Kalarcode'],
    'Kollam': ['Pathanapuram', 'Karunagapally', 'Thodiyoor'],
    'Ernakulam': ['Mattanchery', 'Thoppumbady', 'Kumbalangi'],
    'Wayanad': ['Kalpetta', 'Padinjarathara', 'Meenangadi'],
    'Thrissur': ['Cheruthurithy', 'Vadakkekad', 'Punnayurkkulam']
      // Define sub-areas for other districts here
  };

  // Function to update the branch options based on the selected district
  function updateBranchOptions() {
      const selectedDistrict = districtSelect.value;
      const options = branchOptions[selectedDistrict] || [];
      
      // Clear the existing options
      branchSelect.innerHTML = '';
      
      // Add new options
      options.forEach(option => {
          const optionElement = document.createElement('option');
          optionElement.value = option;
          optionElement.textContent = option;
          branchSelect.appendChild(optionElement);
      });
  }

  // Initial update when the page loads
  updateBranchOptions();

  // Listen for changes in the district dropdown
  districtSelect.addEventListener('change', updateBranchOptions);
</script>


{% endblock %}

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <title>Document</title>
</head>

<body>
    <div class="container">
        <div class="title">Login here</div>
        <div class="content">
            <form action="" method="post">
                {% csrf_token %}
                <div class="user-details">
                    <div class="input-box">
                        <span class="details">Username</span>
                        <input type="text" name="username" placeholder="Enter the username" required>
                    </div>

                    <div class="input-box">
                        <span class="details">Password</span>
                        <input type="password" name="password" placeholder="Enter your password" required>
                    </div>

                </div>

                <div class="button">
                    <input type="submit" value="Login">
                </div>

                <div>
                    <p style="font-weight: bold;">Don't have an account :</p>
                    <a href="{% url 'credentials:signup' %}" role="button" class="aim btn btn-sucess"
                        style="text-decoration: none;">Register</a>
                    <style>
                        a:hover {
                            transform: scale(1.05);
                        }
                    </style>
                </div>
            </form>


            {% for msg in messages %}
            <h2 style="text-align: center;">{{msg}}</h2>
            {% endfor %}
        </div>
    </div>

</body>

</html>

templates/nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>Cial</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- bootstrap css -->
  <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" type="text/css" href="{% static 'styles/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'styles/responsive.css'%}">
  <!-- fevicon -->
  <link rel="icon" href="{% static 'images/fevicon.png' %}" type="image/gif" />
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'styles/jquery.mCustomScrollbar.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/dropdown.css' %}">
  <link rel="stylesheet" href="{% static 'styles/account.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="{% static 'styles/form.css' %}">
  <link rel="stylesheet" href="{% static 'styles/materials.css'%}">
  <link rel="stylesheet" href="{% static 'styles/application.css'%}">
  <!-- owl stylesheets -->
  <link rel="stylesheet" href="{% static 'styles/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
    media="screen">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
</head>

<body>
  <!-- new nabar -->

  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid gap-5">
      <a class="navbar-brand" href="{% url 'bankapp:home' %}"><img src="{% static 'images/download.png' %}"
          style="width: 120px; height: 120px;"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 gap-4">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'bankapp:home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'bankapp:signout' %}">LOGOUT</a>
          </li>

          {% else %}

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'credentials:signin' %}">LOGIN</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'credentials:signup' %}">REGISTER</a>
          </li>

          {% endif %}


          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              BRANCHES
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item"
                  href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
              <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam_district">Kollam</a>
              </li>
              <li><a class="dropdown-item"
                  href="https://en.wikipedia.org/wiki/Ernakulam">Eranakulam</a></li>
              <li><a class="dropdown-item"
                  href="https://en.wikipedia.org/wiki/Wayanad_district">Wayanad</a></li>
              <li><a class="dropdown-item"
                  href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
            </ul>
          </li>

        </ul>

      </div>
    </div>
  </nav>
  {% block body %}


  {% endblock %}

  <div class="footer_section layout_padding" style="background-color: orangered; color: black;">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-sm-6">
          <h4 class="about_text">Contact</h4>
          <div class="location_text"><img src="{% static 'images/map-icon.png' %}"><span
              class="padding_left_15">Kerala</span></div>
          <div class="location_text"><img src="{% static 'images/call-icon.png' %}"><span class="padding_left_15">+01
              9876543210</span></div>
          <div class="location_text"><img src="{% static 'images/mail-icon.png' %}"><span
              class="padding_left_15">federalbank@gmail.com</span></div>
        </div>
        <div class="col-lg-3 col-sm-6">
          <h4 class="about_text">About Financial</h4>
          <p class="dolor_text">ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt</p>
        </div>
        <div class="col-lg-3 col-sm-6">
          <h4 class="about_text">Instagram</h4>
          <div class="footer_images">
            <div class="footer_images_left">
              <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
            </div>
            <div class="footer_images_right">
              <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
              <div class="image_12"><img src="{% static 'images/img-12.png' %}"></div>
            </div>
          </div>
        </div>
        <div class="col-lg-3 col-sm-6">
          <h4 class="about_text">Newsletter</h4>
          <input type="text" class="mail_text" placeholder="Enter your email" name="Enter your email">
          <div class="subscribe_bt"><a href="#">Subscribe</a></div>
          <div class="footer_social_icon">
            <ul>
              <li><a href="#"><img src="{% static 'images/fb-icon1.png' %}"></a></li>
              <li><a href="#"><img src="{% static 'images/twitter-icon1.png' %}"></a></li>
              <li><a href="#"><img src="{% static 'images/linkedin-icon1.png' %}"></a></li>
              <li><a href="#"><img src="{% static 'images/youtub-icon1.png' %}"></a></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- copyright section start -->
      <div class="copyright_section">
        <div class="copyright_text">copyright @ 2023 Federalbank.pvt lmt</a></div>
      </div>
      <!-- copyright section end -->
    </div>
  </div>

</body>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/registration.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="title">Registration</div>
        <div class="content">
            <form action="" method="post">
                {% csrf_token %}
                <div class="user-details">
                    <div class="input-box">
                        <span class="details">Username</span>
                        <input type="text" name="username" placeholder="Enter the username" required>
                    </div>
                    
                    <div class="input-box">
                        <span class="details">Password</span>
                        <input type="password" name="password" placeholder="Enter your password" required>
                    </div>
                    <div class="input-box">
                        <span class="details">Confirm Password</span>
                        <input type="password" name="confirm_password" placeholder="Confirm your password" required>
                    </div>
                </div>

                <div class="button">
                    <input type="submit" value="Submit">
                </div>
            </form>
            {% for msg in messages %}
            <h2 style="text-align: center;">{{msg}}</h2>
            {% endfor %}
        </div>
    </div>
</body>
</html>

templates/success.html
{% extends 'nav.html' %}
{% load static %}
{% block body% }

 <h1>Application submitted</h1>

{% endblock %}